# SPDX-FileCopyrightText: © 2025 ZeldaRET
# SPDX-License-Identifier: CC0-1.0

"""Link the mod object, generate the RecompModTool inputs, and package the .nrm"""

import subprocess
import tomllib
import zipfile
from pathlib import Path

MOD_LD = """\
RAMBASE = 0x81000000;

MEMORY {
    extram(ARWX) : ORIGIN = RAMBASE, LENGTH = 64M
}

SECTIONS {
    /DISCARD/ : { *(.got) *(.MIPS.abiflags) *(.reginfo) *(.pdr) *(.comment) }
}
"""


def toml_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return '"' + v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'
    if isinstance(v, list):
        return "[ " + ", ".join(toml_value(x) for x in v) + " ]"
    if isinstance(v, dict):
        return "{ " + ", ".join(f"{k} = {toml_value(x)}" for k, x in v.items()) + " }"
    raise TypeError(v)


def write_toml(data: dict) -> str:
    """Minimal TOML writer for the mod.toml format (tables, arrays of tables, simple values)"""
    lines = []

    def emit_table(prefix: str, table: dict):
        simple = {k: v for k, v in table.items() if not isinstance(v, dict) and not _is_table_array(v)}
        for k, v in simple.items():
            lines.append(f"{k} = {toml_value(v)}")
        for k, v in table.items():
            if isinstance(v, dict):
                lines.append("")
                lines.append(f"[{prefix}{k}]")
                emit_table(f"{prefix}{k}.", v)
        for k, v in table.items():
            if _is_table_array(v):
                for item in v:
                    lines.append("")
                    lines.append(f"[[{prefix}{k}]]")
                    emit_table(f"{prefix}{k}.", item)

    emit_table("", data)
    return "\n".join(lines) + "\n"


def _is_table_array(v) -> bool:
    return isinstance(v, list) and len(v) > 0 and all(isinstance(x, dict) for x in v)


def write_data_syms(
    vanilla_data_syms: Path,
    out: Path,
    overrides: dict[str, int],
):
    """Write the data reference symbols for the mod: the vanilla ones, with some values overridden
    (moved files and assets), and new symbols added as absolute symbols."""
    data = tomllib.loads(vanilla_data_syms.read_text())
    remaining = dict(overrides)
    lines = ["# Generated by tools/nrm from the vanilla data symbols, with ModMajora's changes", ""]
    for section in data["section"]:
        is_abs = section["name"] == "ABSOLUTE_SYMS"
        symbols = []
        for sym in section.get("symbols", []):
            if sym["name"] in remaining:
                # Moved: emitted as an absolute symbol below
                continue
            symbols.append(sym)
        if is_abs:
            for name, value in sorted(remaining.items()):
                symbols.append({"name": name, "vram": value})
            remaining = {}
        lines.append("[[section]]")
        lines.append(f"name = {toml_value(section['name'])}")
        for key in ("rom", "vram", "size"):
            if key in section:
                lines.append(f"{key} = 0x{section[key]:08X}")
        lines.append("")
        lines.append("symbols = [")
        for sym in symbols:
            lines.append(f"    {{ name = {toml_value(sym['name'])}, vram = 0x{sym['vram'] & 0xFFFFFFFF:08X} }},")
        lines.append("]")
        lines.append("")
    assert not remaining, "no ABSOLUTE_SYMS section in the vanilla data symbols"
    out.write_text("\n".join(lines))


def link_mod(mod_o: Path, out_dir: Path, ld: str = "ld.lld") -> Path:
    ldscript = out_dir / "mod.ld"
    ldscript.write_text(MOD_LD)
    elf = out_dir / "mod.elf"
    subprocess.run(
        [
            ld,
            "-nostdlib",
            "-T",
            str(ldscript),
            "-Map",
            str(out_dir / "mod.map"),
            "--unresolved-symbols=ignore-all",
            "--emit-relocs",
            "-e",
            "0",
            "--no-nmagic",
            "-o",
            str(elf),
            str(mod_o),
        ],
        check=True,
    )
    return elf


def run_mod_tool(
    modtool: Path,
    out_dir: Path,
    manifest: dict,
    mod_filename: str,
    elf: Path,
    func_syms: Path,
    data_syms: list[Path],
    additional_files: list[Path],
) -> Path:
    mod_toml = {
        "manifest": manifest,
        "inputs": {
            "elf_path": str(elf.resolve()),
            "mod_filename": mod_filename,
            "func_reference_syms_file": str(func_syms.resolve()),
            "data_reference_syms_files": [str(p.resolve()) for p in data_syms],
            "additional_files": [str(p.resolve()) for p in additional_files],
        },
    }
    toml_path = out_dir / "mod.toml"
    toml_path.write_text(write_toml(mod_toml))
    nrm_dir = out_dir / "nrm"
    nrm_dir.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run([str(modtool), str(toml_path), str(nrm_dir)], capture_output=True, text=True)
    if proc.returncode != 0 or not (nrm_dir / f"{mod_filename}.nrm").exists():
        raise Exception(f"RecompModTool failed:\n{proc.stdout}\n{proc.stderr}")
    return nrm_dir / f"{mod_filename}.nrm"


def add_files_to_nrm(nrm: Path, files: dict[str, bytes]):
    with zipfile.ZipFile(nrm, "a", compression=zipfile.ZIP_DEFLATED) as z:
        for name, data in files.items():
            z.writestr(name, data)
